version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    depends_on:
      - mlservice
    networks:
      - tripmate-net

  mlservice:
    build: ./ml-service
    container_name: mlservice_container
    ports:
      - "5000:5000"
    networks:
      - tripmate-net

networks:
  tripmate-net:
    driver: bridge
